Server:
  RunMode: debug
  HttpPort: 7771
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://localhost:7742/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxx
  Password: xxx
  IsSSL: true
  From: xxx
  To:
    - xxx
JWT:
  Secret: strongsecret_123456
  Issuer: blog-service
  Expire: 7200
Database:
  DBType: PostgreSQL
  Username: postgres
  Password: K70Vihwgu
  Host: localhost
  Port: 5432
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
